name: tutorial_climate_projections

channels:
  - conda-forge
  - defaults

dependencies:
  - cartopy=0.23.0
  - matplotlib=3.9.1
  - netcdf4=1.7.1
  - numpy=2.0.1
  - pandas=2.2.2
  - rasterio=1.3.10
  - shapely=2.0.5
  - jupyter
  - jupyterlab
